c ----------- prepare data for PSF whisker plot ------------------------
c input x, y, e1, e2 of the stars from given exposure, and the
c       reconstructed PSF on a grid, calculate the difference.
c       Star locations are assumed to be random; We use the PSF at
c       the grid cell where the star is located as the fitted PSF.
c       Star cell information is read in from starRec.
c output x-dx/2, y-dy/2, dx, dy
c gnuplot plots the output by
c   plot 'file.dat' using 1:2:3:4 with vectors head filled lt 2
c
c starXYe12.dat is generated by plotDESpsfDiff.scr
c uses setXYshift()
c-----------------------------------------------------------------------
	program main

        integer nstarMax,nstar,i,IDexp,ichar
        parameter (nstarMax=100000,IDexp=30)
        real*8 x(nstarMax),y(nstarMax),x2,y2,
     c         e1data(nstarMax),e2data(nstarMax),
     c         de1(nstarMax),de2(nstarMax),scale,dum
        character*50 inputStarRec, inputE12recon, outputData, aChar,
     c               inputData, outputDiff

        integer nChips,mc,nc,nShapeLet,im,in,iExp,iChip,npt,ipt
        parameter (nChips=8,mc=10,nc=20,nShapeLet=2)
        parameter (npt=nChips*mc*nc)

        real*8 e1recon(npt),e2recon(npt)
        real*8 dataMask(nstarMax),avg     ! dataMask is not used

        real*8 xShift(nChips),yShift(nChips)
        call setXYshift(xShift,yShift)

        call numToChar(IDexp,aChar,ichar)

        inputStarRec="starXYe12.dat"
        inputE12recon="/data/mzm/BCS/BCS_r_new/reconEM"

        outputData="whiskerData.dat"
        outputDiff="whiskerDiff.dat"

        scale=8000.0

        open(21,file=inputE12recon)
        do i = 1, IDexp-1
          read(21,*)
        enddo
        read(21,*)(e1recon(i),i=1,npt), (e2recon(j),j=1,npt)
        close(21)

        open(20,file=inputStarRec)
        nstar=0
111     continue
          nstar=nstar+1
          read(20,*,end=100)iExp,iChip,im,in,x2,y2,
     c            e1data(nstar),e2data(nstar)
          x(nstar)=x2+xShift(iChip)
          y(nstar)=y2+yShift(iChip)
          ipt=(iChip-1)*mc*nc + (in-1)*mc + im
          de1(nstar)=e1recon(ipt)-e1data(nstar)
          de2(nstar)=e2recon(ipt)-e2data(nstar)
        goto 111

100     continue
        close(20)
        nstar=nstar-1
        write(*,'(A,I5)')"      nstar = ",nstar

        call genWhisker(x,y,e1data,e2data,nstar,dataMask,0,scale,
     c                        outputData,avg)
        write(*,'(A,f12.6)')"      average e  ",avg

        call genWhisker(x,y,de1,de2,nstar,dataMask,0,scale,
     c                        outputDiff,avg)
        write(*,'(A,f12.6)')"      average de ",avg

        stop
        end

c-----------------------------------------------------------------------
        subroutine setXYshift(xShift,yShift)
c
c The parameters need to be the same as calBCSgridXY.f
c-----------------------------------------------------------------------

        integer nChip,dx,dy
        parameter (nChip=8,dx=100,dy=100)

        real*8 xShift(nChip),yShift(nChip)

        xShift(5) = 0
        yShift(5) = 4096 + dy

        xShift(6) = 2048 + dx
        yShift(6) = 4096 + dy

        xShift(7) = 2*(2048 + dx)
        yShift(7) = 4096 + dy

        xShift(8) = 3*(2048 + dx)
        yShift(8) = 4096 + dy

        xShift(1) = 0
        yShift(1) = 0

        xShift(2) = 2048 + dx
        yShift(2) = 0

        xShift(3) = 2*(2048 + dx)
        yShift(3) = 0

        xShift(4) = 3*(2048 + dx)
        yShift(4) = 0

        return
        end
c-----------------------------------------------------------------------
